services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  order-service:
    build: ./OrderServiceNotifications
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;User Id=sa;Password=Your_password123;Database=OrderDb;TrustServerCertificate=True;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    ports:
      - "5000:80"

  notification-service:
    build: ./NotificationService
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ConnectionStrings__NotificationConnection: "Server=sqlserver,1433;User Id=sa;Password=Your_password123;Database=NotificationDb;TrustServerCertificate=True;"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    ports:
      - "5002:80"
